use_frameworks!

def common_install
  pod 'TYHWaterMark', :path => '../'
  pod 'TYHTestUtils',:git=>'https://github.com/pencilCool/TYHTestUtils.git'
end

target 'TYHWaterMark_Tests' do
  common_install
end

target 'StoryBoardDemo' do
  common_install
end

target 'CodeWithNoScene' do
  common_install
end

target 'StoryBoardWithNoScene' do
  common_install
end

# fix bug on xcode14.3 https://blog.csdn.net/crasowas/article/details/129901398
#post_install do |installer|
#  installer.pods_project.targets.each do |target|
#    target.build_configurations.each do |config|
#      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '11.0'
#    end
#  end
#end
